# Types to create
types:
  model:
    name: model
    name_field: MODEL_NAME
    namespace: App\Models
    relative_dir: Models
    file_suffix: php
  controller:
    name: controller
    name_field: CONTROLLER_NAME
    namespace: App\Controllers
    relative_dir: Controllers
    file_suffix: php
  method:
    name: method
    name_field: METHOD_NAME
    namespace: App\Controllers
    relative_dir: Methods
    file_suffix: php
  view:
    name: view
    name_field: VIEW_NAME
    namespace: App\Views
    relative_dir: Views
    file_suffix: php
  migration:
    name: migration
    name_field: CLASS_NAME
    namespace: App\System\Migrations
    relative_dir: System/Migrations
    file_suffix: php
  cron:
    name: cron
    name_field: JOB_NAME
    namespace: App\Jobs\Cron
    relative_dir: Jobs/Cron
    file_suffix: php
  console:
    name: console
    name_field: JOB_NAME
    namespace: App\Jobs\Console
    relative_dir: Jobs/Console
    file_suffix: php
  evlistener:
    name: evlistener
    name_field: EVL_NAME
    namespace: App\System\EventListener
    relative_dir: System/EventListener
    file_suffix: php

